apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - image: academiaonline/webui:test
          name: webui
          ports:
            - containerPort: 8080
