apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hasher
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
        - image: localhost/hasher
          name: hasher
          ports:
            - containerPort: 8080
