name: CI
on: 
  push: 
    branches:
      - main
jobs:
  kubernetes: 
    runs-on: ubuntu-latest    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: docker-login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -p ${DOCKER_PASSWORD} -u ${DOCKER_USERNAME}
      - name: build-hasher
        run: |
          docker build -t academiaonline/hasher:test src/hasher/
          docker push     academiaonline/hasher:test
      - name: build-rng
        run: |
          docker build -t academiaonline/rng:test src/rng/
          docker push     academiaonline/rng:test
      - name: build-webui
        run: |
          docker build -t academiaonline/webui:test src/webui/
          docker push     academiaonline/webui:test
      - name: build-worker
        run: |
          docker build -t academiaonline/worker:test src/worker/
          docker push     academiaonline/worker:test
      - name: minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
          sudo apt-get install ./minikube_latest_amd64.deb
      - name: init
        run: minikube start --driver=docker
      - name: deploy
        run: |
          kubectl apply -f src/hasher/deploy.yaml
          kubectl apply -f src/hasher/svc.yaml
          kubectl apply -f src/redis/sts.yaml
          kubectl apply -f src/redis/svc.yaml
          kubectl apply -f src/rng/ds.yaml
          kubectl apply -f src/rng/svc.yaml
          kubectl apply -f src/webui/deploy.yaml
          kubectl apply -f src/webui/svc.yaml
          kubectl apply -f src/worker/deploy.yaml
      - name: test-redis
        run: |
          while true
          do sleep 10
          kubectl logs sts/redis 2>& 1 | grep Ready.to.accept.connections && break
          done
      - name: deploy-worker
        run: |
          kubectl apply -f src/worker/deploy.yaml
      - name: test-webui
        run: |
          while true
          do sleep 10
          kubectl logs deploy/webui 2>& 1 | grep WEBUI.running && break
          done
      - name: test-worker
        run: |
          while true
          do sleep 10
          kubectl get deploy worker
          kubectl logs deploy/worker 2>& 1
          done
          
          
          
          
          
